# Generated by Django 4.2.16 on 2026-06-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
