# Generated by Django 4.2.16 on 2026-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_syncjob_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='record_totals',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
