# Generated by Django 5.0.4 on 2026-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_syncjob_record_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicAuthState',
            fields=[
                ('state', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code_verifier', models.CharField(max_length=255)),
                ('token_endpoint', models.URLField(max_length=1024)),
                ('organization_alias', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'epic_auth_state',
                'indexes': [models.Index(fields=['expires_at'], name='idx_authstate_expires')],
            },
        ),
    ]
